In [8]:
#dependecis and setup
import pandas as pd
import numpy as np

#Output File
clean_date = "CleanCSV/clean_bed_surge.csv"
#load file
hospital_data = "Resources/bed_surge.csv"

bed_data = pd.read_csv(hospital_data)
bed_data_df = pd.DataFrame(bed_data)
bed_data_df.head()

,status,type_of_facility,county,beds_ready_to_accept_patients,patients_in_beds,beds_in_warm_status,date
0,Ready,Federal Medical Station,Los Angeles,175.0,0,NaN,2020-04-23
1,WrapAround,Federal Medical Station,San Mateo,0.0,0,NaN,2020-04-23
2,TBD,Alternative Care Facility,Tulare,0.0,0,NaN,2020-04-23
3,Ready,Skilled Nursing Facility,San Francisco,11.0,0,NaN,2020-04-23
4,Ready,Ship,Los Angeles,250.0,14,NaN,2020-04-23

In [9]:
bed_data_df.set_index("county", inplace=True)
bed_data_df.head()

,status,type_of_facility,beds_ready_to_accept_patients,patients_in_beds,beds_in_warm_status,date
county,,,,,,
Los Angeles,Ready,Federal Medical Station,175.0,0,NaN,2020-04-23
San Mateo,WrapAround,Federal Medical Station,0.0,0,NaN,2020-04-23
Tulare,TBD,Alternative Care Facility,0.0,0,NaN,2020-04-23
San Francisco,Ready,Skilled Nursing Facility,11.0,0,NaN,2020-04-23
Los Angeles,Ready,Ship,250.0,14,NaN,2020-04-23

In [10]:
clean_data= bed_data_df.loc[['Butte', 'Contra Costa','Fresno','Humboldt', 'Imperial','Los Angeles','Marin','Orange',
                'Riverside', 'Sacramento','San Diego', 'San Francisco', 'San Mateo', 'Santa Clara','Shasta', 'Tulare'],
                    ['beds_ready_to_accept_patients', 'patients_in_beds', 'date']]
clean_data

        beds_ready_to_accept_patients  patients_in_beds        date
county
Butte                           107.0                 0  2020-04-23
Butte                           107.0                 0  2020-04-24
Butte                           107.0                 0  2020-04-25
Butte                           107.0                 0  2020-04-26
Butte                           107.0                 0  2020-04-27
...                               ...               ...         ...
Tulare                            0.0                 0  2020-10-12
Tulare                            0.0                 0  2020-10-13
Tulare                            0.0                 0  2020-10-14
Tulare                            0.0                 0  2020-10-15
Tulare                            0.0                 0  2020-10-16

[2567 rows x 3 columns]

In [11]:
rename_data = clean_data.rename(columns={"beds_ready_to_accept_patients": "Beds Available", "patients_in_beds": "Beds Occupied",
                                        "date": "Date"})
rename_data

        Beds Available  Beds Occupied        Date
county
Butte            107.0              0  2020-04-23
Butte            107.0              0  2020-04-24
Butte            107.0              0  2020-04-25
Butte            107.0              0  2020-04-26
Butte            107.0              0  2020-04-27
...                ...            ...         ...
Tulare             0.0              0  2020-10-12
Tulare             0.0              0  2020-10-13
Tulare             0.0              0  2020-10-14
Tulare             0.0              0  2020-10-15
Tulare             0.0              0  2020-10-16

[2567 rows x 3 columns]

In [12]:
rename_data.to_csv("CleanCSV/clean_bed_surge.csv")